base:
  DO_JEDIATMVAR: "NO"
  DO_JEDIATMENS: "NO"
  DO_JEDIOCNVAR: "NO"
  DO_JEDISNOWDA: "NO"
  DO_MERGENSST: "NO"
  FHMAX_GFS: 840
  BASE_CPLIC: "/lfs/h2/ens/noscrub/neil.barton/ICs"
  KEEPDATA: "NO"
stage_ic:
  USE_OCN_PERTURB_FILES: "true"


